FROM node:20-alpine
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
COPY packages/backend/package.json packages/backend/
RUN npm install
COPY . .
WORKDIR /usr/src/app/packages/backend
CMD ["npm", "run", "start"]
