FROM node:20-alpine
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
COPY packages/frontend/package.json packages/frontend/
RUN npm install
COPY . .
WORKDIR /usr/src/app/packages/frontend
RUN npm run build
CMD ["npm", "run", "start"]
